schema: "src/**/*.graphql"
generates:
  __generated__/schema.generated.ts:
    plugins:
      - add:
          content: |
            // Generated File. Do not change it manually!
            // tslint:disable:no-any
      - typescript
      - typescript-resolvers
    config:
      skipTypename: true
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: keep
      contextType: src/server/types#GraphQLCustomResolversContext
      scalars:
        Void: "void"
      mappers:
        User: src/subdomains/user/data-sources/users.types#UserDocument
        Product: src/subdomains/product/data-sources/product.types#ProductDocument
hooks:
  afterOneFileWrite:
    - tslint --fix
    - prettier --write
